# generated by datamodel-codegen:
#   filename:  bot_hit_bot_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BotHitbotevent(BaseModel):
    victimId: int = Field(..., description='ID of the victim bot that got hit')
    botId: int = Field(..., description='ID of the bot that hit another bot')
    energy: float = Field(..., description='Remaining energy level of the victim bot')
    x: float = Field(..., description='X coordinate of victim bot')
    y: float = Field(..., description='Y coordinate of victim bot')
    rammed: bool = Field(
        ..., description='Flag specifying, if the victim bot got rammed'
    )
