# generated by datamodel-codegen:
#   filename:  bot_death_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BotDeathEvent(BaseModel):
    victimId: int = Field(..., description='ID of the bot that has died')
