# generated by datamodel-codegen:
#   filename:  bullet_hit_bullet_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import bullet_state


class BulletHitBulletEvent(BaseModel):
    bullet: bullet_state.BulletState = Field(
        ..., description='Bullet that hit another bullet'
    )
    hitBullet: bullet_state.BulletState = Field(
        ..., description='The other bullet that was hit by the bullet'
    )
