# generated by datamodel-codegen:
#   filename:  game_ended_event_for_bot.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import bot_results_for_bot


class GameEndedEventForBot(BaseModel):
    numberOfRounds: int = Field(..., description='Number of rounds played')
    results: bot_results_for_bot.BotResultsForBot = Field(
        ..., description='Bot results of the battle'
    )
