# generated by datamodel-codegen:
#   filename:  hit_by_bullet_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import bullet_state


class HitByBulletEvent(BaseModel):
    bullet: bullet_state.BulletState = Field(
        ..., description='Bullet that has hit the bot'
    )
    damage: float = Field(..., description='Damage inflicted by the bullet')
    energy: float = Field(
        ...,
        description='Remaining energy level of the bot after the damage was inflicted',
    )
