# generated by datamodel-codegen:
#   filename:  observer_handshake.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ObserverHandshake(BaseModel):
    name: str = Field(..., description='Name of observer, e.g. Tron Neon 3D Window')
    version: str = Field(..., description='Observer version, e.g. 1.0')
    author: Optional[str] = Field(
        None, description='Author name, e.g. John Doe (john_doe@somewhere.net)'
    )
    secret: Optional[str] = Field(
        None, description='Secret used for access control with the server'
    )
