# generated by datamodel-codegen:
#   filename:  round_ended_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RoundEndedEvent(BaseModel):
    roundNumber: int = Field(
        ..., description='The current round number in the battle when event occurred'
    )
    turnNumber: int = Field(
        ..., description='The current turn number in the round when event occurred'
    )
