# generated by datamodel-codegen:
#   filename:  turn-ready.json
#   timestamp: 2023-10-25T04:35:47+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    pass
