# generated by datamodel-codegen:
#   filename:  bot_handshake.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, constr

from . import initial_position
from .message import MessageType


class BotHandshake(BaseModel):
    type: MessageType = MessageType.BotHandshake
    name: str = Field(..., description='Name of bot, e.g. Killer Bee')
    version: str = Field(..., description='Bot version, e.g. 1.0')
    authors: List[str] = Field(
        ..., description='Name of authors, e.g. John Doe (john_doe@somewhere.net)'
    )
    description: Optional[str] = Field(
        None, description='Short description of the bot, preferable a one-liner'
    )
    homepage: Optional[str] = Field(None, description='URL to a home page for the bot')
    countryCodes: Optional[List[str]] = Field(
        None, description='2-letter country code(s) defined by ISO 3166-1, e.g. "UK"'
    )
    gameTypes: List[str] = Field(
        ...,
        description='Game types supported by this bot (defined elsewhere), e.g. "classic", "melee" and "1v1"',
    )
    platform: Optional[str] = Field(
        None, description='Platform used for running the bot, e.g. JVM 17 or .NET 5'
    )
    programmingLang: Optional[str] = Field(
        None, description='Language used for programming the bot, e.g. Java 17 or C# 10'
    )
    initialPosition: Optional[initial_position.InitialPosition] = Field(
        None, description='Initial start position of the bot used for debugging.'
    )
    secret: Optional[str] = Field(
        None, description='Secret used for access control with the server'
    )
