# generated by datamodel-codegen:
#   filename:  bot_state_with_id.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from robocode_event_models import BotState


class BotStateWithID(BotState):
    id: int = Field(..., description='ID of bot for the observer')
