# generated by datamodel-codegen:
#   filename:  bot_info.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BotInfo(BaseModel):
    host: str = Field(..., description='Host name or IP address')
    port: int = Field(..., description='Port number')
