# generated by datamodel-codegen:
#   filename:  bullet_hit_bot_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import bullet_state


class BulletHitBotEvent(BaseModel):
    victimId: int = Field(..., description='ID of the bot that got hit')
    bullet: bullet_state.BulletState = Field(..., description='Bullet that hit the bot')
    damage: float = Field(..., description='Damage inflicted by the bullet')
    energy: float = Field(
        ..., description='Remaining energy level of the bot that got hit'
    )
