# generated by datamodel-codegen:
#   filename:  bullet_state.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import color


class BulletState(BaseModel):
    bulletId: int = Field(..., description='ID of the bullet')
    ownerId: int = Field(..., description='ID of the bot that fired the bullet')
    power: float = Field(..., description='Bullet firepower (between 0.1 and 3.0)')
    x: float = Field(..., description='X coordinate')
    y: float = Field(..., description='Y coordinate')
    direction: float = Field(..., description='Direction in degrees')
    color: Optional[color.Color] = Field(None, description='Color of the bullet')
