# generated by datamodel-codegen:
#   filename:  event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Event(BaseModel):
    turnNumber: int = Field(
        ..., description='The turn number in current round when event occurred'
    )
