# generated by datamodel-codegen:
#   filename:  game_started_event_for_bot.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from . import game_setup


class GameStartedEventForBot(BaseModel):
    myId: int = Field(..., description='My ID is an unique identifier for this bot')
    gameSetup: game_setup.GameSetup = Field(..., description='Game setup')
