# generated by datamodel-codegen:
#   filename:  message.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class MessageType(Enum):
    BotHandshake = 'BotHandshake'
    ControllerHandshake = 'ControllerHandshake'
    ObserverHandshake = 'ObserverHandshake'
    ServerHandshake = 'ServerHandshake'
    BotReady = 'BotReady'
    BotIntent = 'BotIntent'
    BotInfo = 'BotInfo'
    BotListUpdate = 'BotListUpdate'
    GameStartedEventForBot = 'GameStartedEventForBot'
    GameStartedEventForObserver = 'GameStartedEventForObserver'
    GameEndedEventForBot = 'GameEndedEventForBot'
    GameEndedEventForObserver = 'GameEndedEventForObserver'
    GameAbortedEvent = 'GameAbortedEvent'
    GamePausedEventForObserver = 'GamePausedEventForObserver'
    GameResumedEventForObserver = 'GameResumedEventForObserver'
    RoundStartedEvent = 'RoundStartedEvent'
    RoundEndedEvent = 'RoundEndedEvent'
    ChangeTps = 'ChangeTps'
    TpsChangedEvent = 'TpsChangedEvent'
    BotDeathEvent = 'BotDeathEvent'
    BotHitBotEvent = 'BotHitBotEvent'
    BotHitWallEvent = 'BotHitWallEvent'
    BulletFiredEvent = 'BulletFiredEvent'
    BulletHitBotEvent = 'BulletHitBotEvent'
    BulletHitBulletEvent = 'BulletHitBulletEvent'
    BulletHitWallEvent = 'BulletHitWallEvent'
    HitByBulletEvent = 'HitByBulletEvent'
    ScannedBotEvent = 'ScannedBotEvent'
    SkippedTurnEvent = 'SkippedTurnEvent'
    TickEventForBot = 'TickEventForBot'
    TickEventForObserver = 'TickEventForObserver'
    WonRoundEvent = 'WonRoundEvent'
    StartGame = 'StartGame'
    StopGame = 'StopGame'
    PauseGame = 'PauseGame'
    ResumeGame = 'ResumeGame'
    NextTurn = 'NextTurn'


class Message(BaseModel):
    type: MessageType
