# generated by datamodel-codegen:
#   filename:  round_started_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from robocode_event_models import MessageType


class RoundStartedEvent(BaseModel):
    type: MessageType = MessageType.RoundStartedEvent
    roundNumber: int = Field(
        ..., description='The current round number in the battle when event occurred'
    )
