# generated by datamodel-codegen:
#   filename:  scanned_bot_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from robocode_event_models import MessageType


class ScannedBotEvent(BaseModel):
    type: MessageType = MessageType.ScannedBotEvent
    scannedByBotId: int = Field(..., description='ID of the bot did the scanning')
    scannedBotId: int = Field(..., description='ID of the bot that was scanned')
    energy: float = Field(..., description='Energy level of the scanned bot')
    x: float = Field(..., description='X coordinate of the scanned bot')
    y: float = Field(..., description='Y coordinate of the scanned bot')
    direction: float = Field(..., description='Direction in degrees of the scanned bot')
    speed: float = Field(
        ..., description='Speed measured in units per turn of the scanned bot'
    )
