# generated by datamodel-codegen:
#   filename:  server_handshake.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from robocode_event_models import MessageType


class ServerHandshake(BaseModel):
    type: MessageType = MessageType.ServerHandshake
    sessionId: str = Field(..., description='Unique Session ID')
    name: Optional[str] = Field(
        None, description="Name of server, e.g. John Doe's RoboRumble Server"
    )
    variant: str = Field(
        ..., description="Game variant, e.g. 'Tank Royale' for Robocode Tank Royale"
    )
    version: str = Field(
        ...,
        description="Game version, e.g. '1.0.0' using Semantic Versioning (https://semver.org/)",
    )
    gameTypes: List[str] = Field(
        ...,
        description='Game types running at this server, e.g. "melee" and "1v1"',
        min_items=1,
        unique_items=True,
    )
