# generated by datamodel-codegen:
#   filename:  skipped_turn_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel

from robocode_event_models import MessageType


class SkippedTurnEvent(BaseModel):
    type: MessageType = MessageType.SkippedTurnEvent
    pass
