# generated by datamodel-codegen:
#   filename:  start_game.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from . import bot_address, game_setup, MessageType


class StartGame(BaseModel):
    type: MessageType = MessageType.StartGame
    gameSetup: Optional[game_setup.GameSetup] = Field(None, description='Game setup')
    botAddresses: List[bot_address.BotAddress] = Field(
        ..., description='List of bot addresses'
    )
