# generated by datamodel-codegen:
#   filename:  tick_event_for_bot.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from . import bot_state, bullet_state, event, MessageType


class TickEventForBot(BaseModel):
    type: MessageType = MessageType.TickEventForBot
    roundNumber: int = Field(
        ..., description='The current round number in the battle when event occurred'
    )
    enemyCount: int = Field(
        ..., description='Number of enemies left in the current round'
    )
    botState: bot_state.BotState = Field(..., description='Current state of this bot')
    bulletStates: List[bullet_state.BulletState] = Field(
        ..., description='Current state of the bullets fired by this bot'
    )
    events: List[dict] = Field(
        ..., description='Events occurring in the turn relevant for this bot'
    )
