# generated by datamodel-codegen:
#   filename:  won_round_event.json
#   timestamp: 2022-09-04T05:04:28+00:00

from __future__ import annotations

from pydantic import BaseModel


class WonRoundEvent(BaseModel):
    pass
